# Generated by Django 6.0.3 on 2026-03-10 07:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '发布中'), ('closed', '已关闭')], max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('max_responses', models.IntegerField(default=0)),
                ('ip_limit', models.SmallIntegerField(default=0)),
                ('allow_anonymous', models.SmallIntegerField(default=0)),
                ('is_public_result', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator_id', models.ForeignKey(db_column='creator_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'questionnaire',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('type', models.CharField(choices=[('single', '单选'), ('multiple', '多选'), ('text', '填空'), ('scale', '量表')], max_length=20)),
                ('options', models.JSONField(blank=True, null=True)),
                ('required', models.SmallIntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('logic_rules', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('questionnaire_id', models.ForeignKey(db_column='questionnaire_id', on_delete=django.db.models.deletion.CASCADE, to='questionnaires.questionnaire')),
            ],
            options={
                'db_table': 'question',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('content', models.JSONField()),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'template',
            },
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='template_id',
            field=models.ForeignKey(blank=True, db_column='template_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaires.template'),
        ),
    ]
