# Generated by Django 6.0.3 on 2026-03-10 07:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionnaires', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('temp_data', models.JSONField(blank=True, null=True)),
                ('is_completed', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('questionnaire_id', models.ForeignKey(db_column='questionnaire_id', on_delete=django.db.models.deletion.CASCADE, to='questionnaires.questionnaire')),
                ('respondent_id', models.ForeignKey(blank=True, db_column='respondent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'response',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_id', models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, to='questionnaires.question')),
                ('response_id', models.ForeignKey(db_column='response_id', on_delete=django.db.models.deletion.CASCADE, to='answers.response')),
            ],
            options={
                'db_table': 'answer',
            },
        ),
    ]
